name: Item Service Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: item-service

    steps:
      - uses: actions/checkout@v4

      - name: Build & deploy item service
        run: |
          cd /home/popcornpalace/deployment/stacks/web-project
          docker compose up -d --build --no-deps item-service